[WIP] Add Rocm support
baidu-research/warp-ctc pull request #168
Opened 2021-03-23 08:03 UTC by windstamp

此 PR 还在开发中，请勿合入。

2021-03-23 08:26 UTC, qili93 commented on CMakeLists.txt
> +        ELSE()
这段代码可以不用，ROCM暂时不支持win32

2021-03-23 08:32 UTC, qili93 requested changes

2021-03-23 08:32 UTC, qili93 commented on CMakeLists.txt
>      IF (!WITH_TORCH)
改成IF (!WITH_TORCH AND WITH_GPU) 会出错吗？

2021-03-23 08:32 UTC, qili93 commented on CMakeLists.txt
>      IF (WITH_TORCH)
改成IF (WITH_TORCH AND WITH_GPU) ？

2021-03-23 08:32 UTC, qili93 commented on include/ctc.h
> +#ifdef __CUDACC__
这个__CUDACC__在HIP其实也有定义的，最好写成__HIPCC__这种形式

2021-03-23 08:32 UTC, qili93 commented on include/detail/gpu_ctc.h
>          cuda_status = cudaMemcpyAsync(&(repeats_[start_idx]), repeats,
改成__HIPCC__，后面也一样

2021-03-23 08:32 UTC, qili93 commented on src/ctc_entrypoint.cpp
> +#if (defined(__CUDACC__) || defined(__HIPCC__))
建议顺序换一下，__HIPCC__放前面

2021-03-23 08:32 UTC, qili93 commented on CMakeLists.txt
> +set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
改成类似Paddle的include(hip)？

2021-03-23 08:43 UTC, windstamp commented on CMakeLists.txt
> +set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
后面有 include(hip)，但是需要先通过这行命令指定到哪里找 hip.cmake，否则会找不到。

2021-03-23 08:47 UTC, windstamp commented on CMakeLists.txt
> +        ELSE()
done, thanks.

2021-03-23 08:52 UTC, windstamp commented on CMakeLists.txt
>      IF (!WITH_TORCH)
意思是把
```
    IF (!WITH_TORCH)
        IF (WITH_GPU)
            TARGET_LINK_LIBRARIES(warpctc ${CUDA_curand_LIBRARY})
        ENDIF()
    ENDIF()
```

合成一行吗，这是之前的写法，建议先保留。有个问题，对应的话应该是修改成下面的

```
    IF (!WITH_TORCH)
        IF (WITH_GPU)
            TARGET_LINK_LIBRARIES(warpctc ${CUDA_curand_LIBRARY})
        ENDIF()
        IF (WITH_ROCM)
            TARGET_LINK_LIBRARIES(warpctc ${HIP_hiprand_LIBRARY})
        ENDIF()
    ENDIF()
```

但是，这个宏 CUDA_curand_LIBRARY（以及类似的 HIP_hiprand_LIBRARY），没有找到定义的地方，在项目里面。

项目里面也没有看到使用 curand 库的地方。所以先这样看看，有问题再修改。

2021-03-29 02:36 UTC, qili93 requested changes

2021-03-29 02:36 UTC, qili93 commented on CMakeLists.txt
> +FIND_PACKAGE(Torch QUIET)
这里为什么要修改成QUIET？和ROCM无关的代码我们尽量不修改。

2021-03-29 02:36 UTC, qili93 commented on CMakeLists.txt
> +            hip_add_executable(test_cpu tests/test_cpu.cpp)
这里不需要改成hip_add_executable，正常.cpp或者.cc结尾的文件用add_executable就可以了

2021-03-29 02:36 UTC, qili93 commented on CMakeLists.txt
>      IF (!WITH_TORCH)
好的

2021-03-29 02:36 UTC, qili93 commented on CMakeLists.txt
> +            TARGET_LINK_LIBRARIES(test_gpu warpctc ${hiprand_LIBRARY_DIRS}/libhiprand.so)
这里hiprand_LIBRARY_DIRS的定义，确认在hip.cmake里面能找到

2021-03-29 02:36 UTC, qili93 commented on cmake/hip.cmake
> +# find_package_and_include(miopen)
多余不需要的库删掉

2021-03-29 02:48 UTC, windstamp commented
>>> 这里hiprand_LIBRARY_DIRS的定义，确认在hip.cmake里面能找到

确认是能找到的
```
(base) windstamp@rocm35:/opt/rocm/hiprand/lib/cmake/hiprand ls
hiprand-config.cmake  hiprand-config-version.cmake  hiprand-targets.cmake  hiprand-targets-release.cmake
(base) windstamp@rocm35:/opt/rocm/hiprand/lib/cmake/hiprand grep hiprand_LIBRARY_DIRS -r *
hiprand-config.cmake:#   hiprand_LIBRARY_DIRS     - Link directory for hipRAND library.
hiprand-config.cmake:set_and_check(hiprand_LIBRARY_DIRS "${PACKAGE_PREFIX_DIR}/hiprand/lib" )
```

2021-03-29 02:49 UTC, windstamp commented
>>> 多余不需要的库删掉
done, thanks.

2021-03-29 07:28 UTC, windstamp commented
>>> 这里不需要改成hip_add_executable，正常.cpp或者.cc结尾的文件用add_executable就可以了
done, thanks.

2021-03-29 07:42 UTC, qili93 commented on include/ctc.h
> +#endif
这里把CUstream命名为GPUstream会更加合适一点，因为typedef struct CUstream_st* CUstream;是CUDA本身的一个定义，以防万一和这个头文件被其他文件include之前或者之后引用了cuda的头文件，会导致这个定义失效，最好定义成GPUstream就可以避免这个问题。

2021-03-29 07:51 UTC, windstamp commented
>>> 这里把CUstream命名为GPUstream会更加合适一点，因为typedef struct CUstream_st* CUstream;是CUDA本身的一个定义，以防万一和这个头文件被其他文件include之前或者之后引用了cuda的头文件，会导致这个定义失效，最好定义成GPUstream就可以避免这个问题。
done, thanks.

2021-03-29 08:35 UTC, qili93 approved these changes
LGTM

2021-03-30 01:48 UTC, merged